/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agileassignment2;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class GenerateInvoice extends javax.swing.JFrame {

    double sum = 0;
    
    /**
     * Creates new form GenerateInvoice
     */
    public GenerateInvoice() {
        initComponents();
        clearAll();
    }

    public class CustOrder{
        public String id;
        public String orderDate;
        public String custID;
        public String productID;
        public String productName;
        public int quantity;
        public double productPrice;

        public CustOrder(String id, String orderDate, String custID, String productID, String productName, int quantity, double productPrice) {
            this.id = id;
            this.orderDate = orderDate;
            this.custID = custID;
            this.productID = productID;
            this.productName = productName;
            this.quantity = quantity;
            this.productPrice = productPrice;
        }
        
    }
    
    public ArrayList ProductList(){
        ArrayList<CustOrder> list = new ArrayList<CustOrder>();
        CustOrder order1 = new CustOrder("OR0001","6/6/2018","CR0001","P1001","Rose",3,10.0);
        CustOrder order2 = new CustOrder("OR0002","6/8/2018","CR0002","P1001","Rose",5,10.0);
        CustOrder order3 = new CustOrder("OR0003","21/8/2018","CR0002","P1002","Sun Flowers",1,10.0);
        CustOrder order4 = new CustOrder("OR0004","8/9/2018","CR0001","P1001","Rose",1,10.0);
        CustOrder order5 = new CustOrder("OR0005","22/9/2018","CR0001","P1002","Sun Flowers",7,10.0);
        CustOrder order6 = new CustOrder("OR0006","6/1/2019","CR0001","P1001","Rose",5,10.0);
        
        list.add(order1);
        list.add(order2);
        list.add(order3);
        list.add(order4);
        list.add(order5);
        list.add(order6);
        return list;
    }
    
    public void ShowTable(String custID){
        try{
        DefaultTableModel model = (DefaultTableModel)jtOrder.getModel();
        ArrayList<CustOrder> list = ProductList();
        Object rowData[] = new Object[7];
        double totalPrice = 0;
        
        String sFromDate = "7/" + selectedMonth() + "/2018";
        String sToDate = "6/" + nextMonth();
        Date fromDate = new SimpleDateFormat("dd/MM/yyyy").parse(sFromDate);
        Date toDate = new SimpleDateFormat("dd/MM/yyyy").parse(sToDate);
        
        sum = 0;
        model.setRowCount(0);
        
        for(int i=0;i<list.size();i++){
            if(custID.equals(list.get(i).custID)){
                Date orderDate = new SimpleDateFormat("dd/MM/yyyy").parse(list.get(i).orderDate);
                
                //orderDate compare the fromDate and toDate
                if(orderDate.compareTo(fromDate) >= 0 && orderDate.compareTo(toDate) <= 0){
                    
                totalPrice = list.get(i).quantity * list.get(i).productPrice;
                
                rowData[0] = list.get(i).id;
                rowData[1] = list.get(i).orderDate;
                rowData[2] = list.get(i).productID;
                rowData[3] = list.get(i).productName;
                rowData[4] = list.get(i).quantity;
                rowData[5] = list.get(i).productPrice;
                rowData[6] = totalPrice;
                
                sum += totalPrice;
                model.addRow(rowData);
                
                }
            }
        }
        jtfTotalAmount.setText("RM" + String.format("%.2f", sum));
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Date has problem","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblCompanyName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jlblMonth = new javax.swing.JLabel();
        jlblCustID = new javax.swing.JLabel();
        jcbCorporateCustID = new javax.swing.JComboBox<>();
        jcbMonth = new javax.swing.JComboBox<>();
        jlblCorporateCustName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jlblAddress = new javax.swing.JLabel();
        jlblInvoice = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaAddress = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtOrder = new javax.swing.JTable();
        jlblTotalAmount = new javax.swing.JLabel();
        jtfTotalAmount = new javax.swing.JTextField();
        jbGenerate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 255));

        jlblCompanyName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblCompanyName.setText("Fiore FlowerShop");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblCompanyName)
                .addGap(278, 278, 278))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jlblCompanyName)
                .addGap(29, 29, 29))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jlblMonth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblMonth.setText("Month:");

        jlblCustID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblCustID.setText("Corporate Customer ID:");

        jcbCorporateCustID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbCorporateCustID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CR0001", "CR0002" }));
        jcbCorporateCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCorporateCustIDActionPerformed(evt);
            }
        });

        jcbMonth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jcbMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMonthActionPerformed(evt);
            }
        });

        jlblCorporateCustName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblCorporateCustName.setText("Corporate Customer Name:");

        jtfName.setEditable(false);
        jtfName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlblAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblAddress.setText("Corporate Customer Address:");

        jlblInvoice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblInvoice.setText("Invoice Information");

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jtaAddress.setEditable(false);
        jtaAddress.setColumns(20);
        jtaAddress.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtaAddress.setRows(5);
        jScrollPane1.setViewportView(jtaAddress);

        jtOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Date", "Product ID", "Product Name", "Quantity", "Product Price", "Total Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtOrder);

        jlblTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlblTotalAmount.setText("Total Amount:");

        jtfTotalAmount.setEditable(false);
        jtfTotalAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jbGenerate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbGenerate.setText("Generate Invoice");
        jbGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblTotalAmount)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(jlblInvoice))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblAddress)
                                    .addComponent(jlblCorporateCustName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlblCustID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbCorporateCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlblMonth)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(100, 100, 100)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jbGenerate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblInvoice)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblMonth)
                    .addComponent(jcbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCustID)
                    .addComponent(jcbCorporateCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCorporateCustName)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTotalAmount))
                .addGap(18, 18, 18)
                .addComponent(jbGenerate)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbCorporateCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCorporateCustIDActionPerformed
        // TODO add your handling code here:
        ShowTable(jcbCorporateCustID.getSelectedItem().toString());
        setCustText(jcbCorporateCustID.getSelectedItem().toString());
    }//GEN-LAST:event_jcbCorporateCustIDActionPerformed

    private void jbGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerateActionPerformed
        // TODO add your handling code here:
        clearAll();
        JOptionPane.showMessageDialog(null,"Success generate Invoice","Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbGenerateActionPerformed

    private void jcbMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMonthActionPerformed
        // TODO add your handling code here:
        if(!jtfName.getText().equals("")){
            ShowTable(jcbCorporateCustID.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jcbMonthActionPerformed

    private void setCustText(String selectedCustID){
        if(selectedCustID.equals("CR0001")){
            jtfName.setText("Andrew Chong");
            jtaAddress.setText("No 123,Jalan Klang,41300 Kuala Lumpur");
        }
        else if(selectedCustID.equals("CR0002")){
            jtfName.setText("Leo Lo");
            jtaAddress.setText("No 124,Jalan Klang,41300 Kuala Lumpur");
        }
    }
    
    private void clearAll(){
        DefaultTableModel model = (DefaultTableModel)jtOrder.getModel();
        model.setRowCount(0);
        jtfTotalAmount.setText("");
        jtfName.setText("");
        jtaAddress.setText("");
    }
    
    private int selectedMonth(){
        int selectedMonth = 1;
        String month = jcbMonth.getSelectedItem().toString();
        if(month.equals("January")){
            selectedMonth = 1;
        }
        else if(month.equals("February")){
            selectedMonth = 2;
        }
        else if(month.equals("March")){
            selectedMonth = 3;
        }
        else if(month.equals("April")){
            selectedMonth = 4;
        }
        else if(month.equals("May")){
            selectedMonth = 5;
        }
        else if(month.equals("June")){
            selectedMonth = 6;
        }
        else if(month.equals("July")){
            selectedMonth = 7;
        }
        else if(month.equals("August")){
            selectedMonth = 8;
        }
        else if(month.equals("September")){
            selectedMonth = 9;
        }
        else if(month.equals("October")){
            selectedMonth = 10;
        }
        else if(month.equals("November")){
            selectedMonth = 11;
        }
        else if(month.equals("December")){
            selectedMonth = 12;
        }
        return selectedMonth;
    }
    
    private String nextMonth(){
        String month = "1/2018";
        int getMonth = selectedMonth();
        if(getMonth == 1 || getMonth == 2 || getMonth == 3 || getMonth == 4 || getMonth == 5 || getMonth == 6 ||
           getMonth == 7 || getMonth == 8 || getMonth == 9 || getMonth == 11){
            getMonth = getMonth + 1;
            month = getMonth + "/2018";
        }else if(getMonth == 12){
            month = "1/2019";
        }
        return month;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbGenerate;
    private javax.swing.JComboBox<String> jcbCorporateCustID;
    private javax.swing.JComboBox<String> jcbMonth;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JLabel jlblCompanyName;
    private javax.swing.JLabel jlblCorporateCustName;
    private javax.swing.JLabel jlblCustID;
    private javax.swing.JLabel jlblInvoice;
    private javax.swing.JLabel jlblMonth;
    private javax.swing.JLabel jlblTotalAmount;
    private javax.swing.JTable jtOrder;
    private javax.swing.JTextArea jtaAddress;
    private javax.swing.JTextField jtfName;
    private javax.swing.JTextField jtfTotalAmount;
    // End of variables declaration//GEN-END:variables
}
